# Generated by Django 3.0.5 on 2020-04-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matric', models.CharField(max_length=120, verbose_name='Matric')),
                ('Inter', models.CharField(max_length=120, verbose_name='Inter')),
                ('Gradute', models.CharField(max_length=120, verbose_name='Gradute')),
                ('Other', models.CharField(max_length=120, verbose_name='Other')),
                ('College', models.CharField(max_length=120, verbose_name='College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='QualificationDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNo', models.PositiveIntegerField(verbose_name='Mobile No')),
                ('Image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120, verbose_name='first name')),
                ('LastName', models.CharField(max_length=120, verbose_name='last name')),
                ('Father', models.CharField(max_length=120, verbose_name='father name')),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('transgender', 'TRANSGENDER')], max_length=20, verbose_name='gender')),
                ('Dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PersonalDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=120, verbose_name='site')),
                ('City', models.CharField(max_length=120, verbose_name='city')),
                ('District', models.CharField(max_length=120, verbose_name='district')),
                ('Village', models.CharField(blank=True, max_length=120, verbose_name='village')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LocationDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
