# Generated by Django 3.0.5 on 2020-04-24 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setupprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='Image',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/Avatar.png', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
