# Generated by Django 3.0.5 on 2020-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
