# Generated by Django 3.0.5 on 2020-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.IntegerField()),
                ('Query', models.TextField(max_length=500)),
            ],
        ),
    ]
