# Generated by Django 3.0.5 on 2021-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
