# Generated by Django 3.0.5 on 2021-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
