# Generated by Django 3.0.5 on 2021-07-11 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
