# Generated by Django 3.0.5 on 2021-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210711_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='contactus',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
