# Generated by Django 3.0.5 on 2020-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuryamandirDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuryamandirExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyName', models.CharField(max_length=120)),
                ('ItemName', models.CharField(max_length=120)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
